port: 4000
host: localhost
safe: false

### site serving configuration ###

#serve .md files without trailing slash
permalink: /:categories/:title

exclude: [CNAME, README.md, .gitignore, vendor]
include: ['de/', 'en/', 'fr/', 'in/', 'ja/']
timezone: null
lsi: false
google_analytics_key: UA-74055103-1 ## put YOUR key here to enable tracking! (blank to disable)
favicon: /jabref.ico #put a path like: "img/favicon.ico"

plugins:
  - jekyll-sitemap

#pygments is not supported by GitHub. See https://help.github.com/articles/page-build-failed-config-file-error/#fixing-highlighting-errors
#See also https://github.com/blog/2100-github-pages-now-faster-and-simpler-with-jekyll-3-0
#We have to use rouge
#http://idratherbewriting.com/2016/02/21/bug-with-kramdown-and-rouge-with-github-pages/
highlighter: rouge
markdown: kramdown
kramdown:
  input: GFM
  auto_ids: true
  syntax_highlighter: rouge

sass:
  sass_dir: _sass

defaults:
  -
    scope:
      path: "" # empty string for all files
    values:
      layout: "default"
